"""explicit chunk 1 schema

Revision ID: aae7241f909a
Revises: 0001_initial
Create Date: 2026-08-25 13:31:44.487067
"""
from typing import Sequence, Union

from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa


revision: str = 'aae7241f909a'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpora',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corpora'))
    )
    with op.batch_alter_table('corpora', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corpora_name'), ['name'], unique=False)

    op.create_table('jobs',
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('input_reference', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='job_status', native_enum=False), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_artifact_ids', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('progress_current >= 0', name=op.f('ck_jobs_progress_current_nonnegative')),
    sa.CheckConstraint('progress_total >= 0', name=op.f('ck_jobs_progress_total_nonnegative')),
    sa.CheckConstraint('retry_count >= 0', name=op.f('ck_jobs_retry_count_nonnegative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('corpus_versions',
    sa.Column('corpus_id', sa.Uuid(), nullable=False),
    sa.Column('version_label', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('draft', 'indexing', 'ready', 'failed', 'archived', name='corpus_version_status', native_enum=False), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('parser_configuration', sa.JSON(), nullable=False),
    sa.Column('chunker_configuration', sa.JSON(), nullable=False),
    sa.Column('embedding_configuration', sa.JSON(), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('document_count >= 0', name=op.f('ck_corpus_versions_document_count_nonnegative')),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpora.id'], name=op.f('fk_corpus_versions_corpus_id_corpora'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corpus_versions')),
    sa.UniqueConstraint('corpus_id', 'version_label', name=op.f('uq_corpus_versions_corpus_id'))
    )
    with op.batch_alter_table('corpus_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corpus_versions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_corpus_versions_corpus_id'), ['corpus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corpus_versions_status'), ['status'], unique=False)

    op.create_table('search_indexes',
    sa.Column('corpus_version_id', sa.Uuid(), nullable=False),
    sa.Column('index_type', sa.Enum('lexical', 'dense', name='search_index_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'building', 'ready', 'failed', name='search_index_status', native_enum=False), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('configuration_hash', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('preprocessing_version', sa.String(length=255), nullable=True),
    sa.Column('similarity_method', sa.String(length=50), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('indexed_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('chunk_count >= 0', name=op.f('ck_search_indexes_chunk_count_nonnegative')),
    sa.CheckConstraint('failure_count >= 0', name=op.f('ck_search_indexes_failure_count_nonnegative')),
    sa.CheckConstraint('indexed_count >= 0', name=op.f('ck_search_indexes_indexed_count_nonnegative')),
    sa.ForeignKeyConstraint(['corpus_version_id'], ['corpus_versions.id'], name=op.f('fk_search_indexes_corpus_version_id_corpus_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_indexes')),
    sa.UniqueConstraint('corpus_version_id', 'index_type', 'configuration_hash', name=op.f('uq_search_indexes_corpus_version_id'))
    )
    with op.batch_alter_table('search_indexes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_indexes_corpus_version_id'), ['corpus_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_indexes_status'), ['status'], unique=False)

    op.create_table('source_documents',
    sa.Column('corpus_version_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('license_information', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('parse_status', sa.Enum('pending', 'parsing', 'ready', 'failed', name='document_parse_status', native_enum=False), nullable=False),
    sa.Column('parse_warnings', sa.JSON(), nullable=False),
    sa.Column('metadata_provenance', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['corpus_version_id'], ['corpus_versions.id'], name=op.f('fk_source_documents_corpus_version_id_corpus_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_documents')),
    sa.UniqueConstraint('corpus_version_id', 'file_hash', name=op.f('uq_source_documents_corpus_version_id'))
    )
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_documents_corpus_version_id'), ['corpus_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_documents_file_hash'), ['file_hash'], unique=False)

    op.create_table('artifacts',
    sa.Column('corpus_version_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('producing_operation', sa.String(length=255), nullable=False),
    sa.Column('producer_version', sa.String(length=255), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['corpus_version_id'], ['corpus_versions.id'], name=op.f('fk_artifacts_corpus_version_id_corpus_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], name=op.f('fk_artifacts_document_id_source_documents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_artifacts_job_id_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_artifacts_storage_key'))
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_artifact_type'), ['artifact_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_corpus_version_id'), ['corpus_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_job_id'), ['job_id'], unique=False)

    op.create_table('chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('corpus_version_id', sa.Uuid(), nullable=False),
    sa.Column('chunker_id', sa.String(length=255), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('section_path', sa.JSON(), nullable=False),
    sa.Column('source_element_ids', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('token_count >= 0', name=op.f('ck_chunks_token_count_nonnegative')),
    sa.ForeignKeyConstraint(['corpus_version_id'], ['corpus_versions.id'], name=op.f('fk_chunks_corpus_version_id_corpus_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], name=op.f('fk_chunks_document_id_source_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks')),
    sa.UniqueConstraint('corpus_version_id', 'id', name=op.f('uq_chunks_corpus_version_id')),
    sa.UniqueConstraint('document_id', 'chunker_id', 'sequence_number', name=op.f('uq_chunks_document_id'))
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunks_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_corpus_version_id'), ['corpus_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index('ix_chunks_version_document', ['corpus_version_id', 'document_id'], unique=False)

    op.create_table('document_elements',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('parent_element_id', sa.Uuid(), nullable=True),
    sa.Column('element_type', sa.String(length=50), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_path', sa.JSON(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('parser_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], name=op.f('fk_document_elements_document_id_source_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_element_id'], ['document_elements.id'], name=op.f('fk_document_elements_parent_element_id_document_elements'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_elements')),
    sa.UniqueConstraint('document_id', 'sequence_number', name=op.f('uq_document_elements_document_id'))
    )
    with op.batch_alter_table('document_elements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_elements_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_elements_parent_element_id'), ['parent_element_id'], unique=False)

    op.create_table('index_entries',
    sa.Column('index_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('searchable_text', sa.Text(), nullable=True),
    sa.Column('embedding', sa.JSON().with_variant(Vector(), 'postgresql'), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_index_entries_chunk_id_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['index_id'], ['search_indexes.id'], name=op.f('fk_index_entries_index_id_search_indexes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_index_entries')),
    sa.UniqueConstraint('index_id', 'chunk_id', name=op.f('uq_index_entries_index_id'))
    )
    with op.batch_alter_table('index_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_index_entries_chunk_id'), ['chunk_id'], unique=False)
        batch_op.create_index('ix_index_entries_index_chunk', ['index_id', 'chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_index_entries_index_id'), ['index_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('index_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_index_entries_index_id'))
        batch_op.drop_index('ix_index_entries_index_chunk')
        batch_op.drop_index(batch_op.f('ix_index_entries_chunk_id'))

    op.drop_table('index_entries')
    with op.batch_alter_table('document_elements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_elements_parent_element_id'))
        batch_op.drop_index(batch_op.f('ix_document_elements_document_id'))

    op.drop_table('document_elements')
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index('ix_chunks_version_document')
        batch_op.drop_index(batch_op.f('ix_chunks_document_id'))
        batch_op.drop_index(batch_op.f('ix_chunks_corpus_version_id'))
        batch_op.drop_index(batch_op.f('ix_chunks_content_hash'))

    op.drop_table('chunks')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_job_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_document_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_corpus_version_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_content_hash'))
        batch_op.drop_index(batch_op.f('ix_artifacts_artifact_type'))

    op.drop_table('artifacts')
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_documents_file_hash'))
        batch_op.drop_index(batch_op.f('ix_source_documents_corpus_version_id'))

    op.drop_table('source_documents')
    with op.batch_alter_table('search_indexes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_indexes_status'))
        batch_op.drop_index(batch_op.f('ix_search_indexes_corpus_version_id'))

    op.drop_table('search_indexes')
    with op.batch_alter_table('corpus_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corpus_versions_status'))
        batch_op.drop_index(batch_op.f('ix_corpus_versions_corpus_id'))
        batch_op.drop_index(batch_op.f('ix_corpus_versions_content_hash'))

    op.drop_table('corpus_versions')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_jobs_idempotency_key'))

    op.drop_table('jobs')
    with op.batch_alter_table('corpora', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corpora_name'))

    op.drop_table('corpora')
    # ### end Alembic commands ###
