"""chunk 2 pipeline runtime

Revision ID: d232e4908b27
Revises: aae7241f909a
Create Date: 2026-08-25 14:44:10.792202
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd232e4908b27'
down_revision: Union[str, None] = 'aae7241f909a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_configurations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('retrieval_mode', sa.Enum('none', 'lexical', 'dense', 'hybrid', name='retrieval_mode', native_enum=False), nullable=False),
    sa.Column('lexical_configuration', sa.JSON(), nullable=False),
    sa.Column('dense_configuration', sa.JSON(), nullable=False),
    sa.Column('fusion_configuration', sa.JSON(), nullable=False),
    sa.Column('reranker_configuration', sa.JSON(), nullable=False),
    sa.Column('query_processing_configuration', sa.JSON(), nullable=False),
    sa.Column('context_configuration', sa.JSON(), nullable=False),
    sa.Column('generation_configuration', sa.JSON(), nullable=False),
    sa.Column('citation_configuration', sa.JSON(), nullable=False),
    sa.Column('prompt_versions', sa.JSON(), nullable=False),
    sa.Column('configuration_hash', sa.String(length=64), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_configurations')),
    sa.UniqueConstraint('name', 'version', name=op.f('uq_pipeline_configurations_name'))
    )
    with op.batch_alter_table('pipeline_configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_configurations_configuration_hash'), ['configuration_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_configurations_frozen_at'), ['frozen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_configurations_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_configurations_retrieval_mode'), ['retrieval_mode'], unique=False)

    op.create_table('prompt_templates',
    sa.Column('prompt_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_templates')),
    sa.UniqueConstraint('prompt_id', 'version', name=op.f('uq_prompt_templates_prompt_id'))
    )
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_templates_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_templates_frozen_at'), ['frozen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_templates_prompt_id'), ['prompt_id'], unique=False)

    op.create_table('query_runs',
    sa.Column('corpus_version_id', sa.Uuid(), nullable=False),
    sa.Column('benchmark_question_id', sa.Uuid(), nullable=True),
    sa.Column('pipeline_configuration_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_template_id', sa.Uuid(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('normalized_query', sa.Text(), nullable=False),
    sa.Column('rewritten_query', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='query_run_status', native_enum=False), nullable=False),
    sa.Column('route_decision', sa.JSON(), nullable=False),
    sa.Column('classification', sa.JSON(), nullable=False),
    sa.Column('extracted_metadata', sa.JSON(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answerability_decision', sa.Enum('answerable', 'partially_answerable', 'unanswerable', name='answerability', native_enum=False), nullable=True),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('abstention_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('generation_metadata', sa.JSON(), nullable=False),
    sa.Column('context_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('raw_response_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['context_artifact_id'], ['artifacts.id'], name=op.f('fk_query_runs_context_artifact_id_artifacts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['corpus_version_id'], ['corpus_versions.id'], name=op.f('fk_query_runs_corpus_version_id_corpus_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pipeline_configuration_id'], ['pipeline_configurations.id'], name=op.f('fk_query_runs_pipeline_configuration_id_pipeline_configurations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], name=op.f('fk_query_runs_prompt_template_id_prompt_templates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raw_response_artifact_id'], ['artifacts.id'], name=op.f('fk_query_runs_raw_response_artifact_id_artifacts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_query_runs'))
    )
    with op.batch_alter_table('query_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_query_runs_answerability_decision'), ['answerability_decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_runs_benchmark_question_id'), ['benchmark_question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_runs_context_artifact_id'), ['context_artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_runs_corpus_version_id'), ['corpus_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_runs_failure_code'), ['failure_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_runs_pipeline_configuration_id'), ['pipeline_configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_runs_prompt_template_id'), ['prompt_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_runs_raw_response_artifact_id'), ['raw_response_artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_runs_status'), ['status'], unique=False)

    op.create_table('context_sources',
    sa.Column('query_run_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('citation_id', sa.String(length=30), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=50), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_context_sources_chunk_id_chunks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], name=op.f('fk_context_sources_document_id_source_documents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['query_run_id'], ['query_runs.id'], name=op.f('fk_context_sources_query_run_id_query_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_context_sources')),
    sa.UniqueConstraint('query_run_id', 'chunk_id', name=op.f('uq_context_sources_query_run_id'))
    )
    with op.batch_alter_table('context_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_sources_chunk_id'), ['chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_sources_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_sources_exclusion_reason'), ['exclusion_reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_sources_query_run_id'), ['query_run_id'], unique=False)
        batch_op.create_index('ix_context_sources_run_selected', ['query_run_id', 'selected'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_sources_selected'), ['selected'], unique=False)

    op.create_table('generated_claims',
    sa.Column('query_run_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('citation_ids', sa.JSON(), nullable=False),
    sa.Column('support_status', sa.Enum('supported', 'partially_supported', 'unsupported', 'contradicted', 'not_evaluated', name='claim_support_status', native_enum=False), nullable=False),
    sa.Column('verification_method', sa.String(length=100), nullable=False),
    sa.Column('verification_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['query_run_id'], ['query_runs.id'], name=op.f('fk_generated_claims_query_run_id_query_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_claims')),
    sa.UniqueConstraint('query_run_id', 'sequence_number', name=op.f('uq_generated_claims_query_run_id'))
    )
    with op.batch_alter_table('generated_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_claims_query_run_id'), ['query_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_claims_support_status'), ['support_status'], unique=False)

    op.create_table('retrieval_results',
    sa.Column('query_run_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('retriever_type', sa.String(length=50), nullable=False),
    sa.Column('original_rank', sa.Integer(), nullable=True),
    sa.Column('original_score', sa.Float(), nullable=True),
    sa.Column('normalized_score', sa.Float(), nullable=True),
    sa.Column('fused_rank', sa.Integer(), nullable=True),
    sa.Column('fusion_score', sa.Float(), nullable=True),
    sa.Column('reranked_rank', sa.Integer(), nullable=True),
    sa.Column('reranker_score', sa.Float(), nullable=True),
    sa.Column('selected_for_context', sa.Boolean(), nullable=False),
    sa.Column('timing_ms', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_retrieval_results_chunk_id_chunks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['query_run_id'], ['query_runs.id'], name=op.f('fk_retrieval_results_query_run_id_query_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retrieval_results')),
    sa.UniqueConstraint('query_run_id', 'chunk_id', 'retriever_type', name=op.f('uq_retrieval_results_query_run_id'))
    )
    with op.batch_alter_table('retrieval_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retrieval_results_chunk_id'), ['chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retrieval_results_query_run_id'), ['query_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retrieval_results_retriever_type'), ['retriever_type'], unique=False)
        batch_op.create_index('ix_retrieval_results_run_type_rank', ['query_run_id', 'retriever_type', 'original_rank'], unique=False)

    op.create_table('citations',
    sa.Column('query_run_id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('citation_id', sa.String(length=30), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('referenced_text', sa.Text(), nullable=False),
    sa.Column('entailment_status', sa.String(length=50), nullable=False),
    sa.Column('entailment_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_citations_chunk_id_chunks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['claim_id'], ['generated_claims.id'], name=op.f('fk_citations_claim_id_generated_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], name=op.f('fk_citations_document_id_source_documents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['query_run_id'], ['query_runs.id'], name=op.f('fk_citations_query_run_id_query_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citations')),
    sa.UniqueConstraint('claim_id', 'citation_id', name=op.f('uq_citations_claim_id'))
    )
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citations_chunk_id'), ['chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citations_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citations_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citations_query_run_id'), ['query_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citations_query_run_id'))
        batch_op.drop_index(batch_op.f('ix_citations_document_id'))
        batch_op.drop_index(batch_op.f('ix_citations_claim_id'))
        batch_op.drop_index(batch_op.f('ix_citations_chunk_id'))

    op.drop_table('citations')
    with op.batch_alter_table('retrieval_results', schema=None) as batch_op:
        batch_op.drop_index('ix_retrieval_results_run_type_rank')
        batch_op.drop_index(batch_op.f('ix_retrieval_results_retriever_type'))
        batch_op.drop_index(batch_op.f('ix_retrieval_results_query_run_id'))
        batch_op.drop_index(batch_op.f('ix_retrieval_results_chunk_id'))

    op.drop_table('retrieval_results')
    with op.batch_alter_table('generated_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_claims_support_status'))
        batch_op.drop_index(batch_op.f('ix_generated_claims_query_run_id'))

    op.drop_table('generated_claims')
    with op.batch_alter_table('context_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_sources_selected'))
        batch_op.drop_index('ix_context_sources_run_selected')
        batch_op.drop_index(batch_op.f('ix_context_sources_query_run_id'))
        batch_op.drop_index(batch_op.f('ix_context_sources_exclusion_reason'))
        batch_op.drop_index(batch_op.f('ix_context_sources_document_id'))
        batch_op.drop_index(batch_op.f('ix_context_sources_chunk_id'))

    op.drop_table('context_sources')
    with op.batch_alter_table('query_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_query_runs_status'))
        batch_op.drop_index(batch_op.f('ix_query_runs_raw_response_artifact_id'))
        batch_op.drop_index(batch_op.f('ix_query_runs_prompt_template_id'))
        batch_op.drop_index(batch_op.f('ix_query_runs_pipeline_configuration_id'))
        batch_op.drop_index(batch_op.f('ix_query_runs_failure_code'))
        batch_op.drop_index(batch_op.f('ix_query_runs_corpus_version_id'))
        batch_op.drop_index(batch_op.f('ix_query_runs_context_artifact_id'))
        batch_op.drop_index(batch_op.f('ix_query_runs_benchmark_question_id'))
        batch_op.drop_index(batch_op.f('ix_query_runs_answerability_decision'))

    op.drop_table('query_runs')
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_templates_prompt_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_templates_frozen_at'))
        batch_op.drop_index(batch_op.f('ix_prompt_templates_content_hash'))

    op.drop_table('prompt_templates')
    with op.batch_alter_table('pipeline_configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_configurations_retrieval_mode'))
        batch_op.drop_index(batch_op.f('ix_pipeline_configurations_name'))
        batch_op.drop_index(batch_op.f('ix_pipeline_configurations_frozen_at'))
        batch_op.drop_index(batch_op.f('ix_pipeline_configurations_configuration_hash'))

    op.drop_table('pipeline_configurations')
    # ### end Alembic commands ###
